/// Flutter icons PatchworkIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PatchworkIcons
///      fonts:
///       - asset: fonts/PatchworkIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class PatchworkIcons {
  PatchworkIcons._();

  static const _kFontFam = 'PatchworkIcons';

  static const IconData award = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData button_icon = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData thimble = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData clothing_stitches = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData lootbox_closed = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData lootbox_open = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData award_1 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData cup = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData success = const IconData(0xe813, fontFamily: _kFontFam);
}
